// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4errorModel2cellTypes_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4errorModel2cellTypesHeirar_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4indSigmat_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4indSigmatHyperprior_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4indSigmatHyperpriorInequal_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4errorModel2cellTypes_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4errorModel2cellTypes_mod, 0},
    {"_rcpp_module_boot_stan_fit4errorModel2cellTypesHeirar_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4errorModel2cellTypesHeirar_mod, 0},
    {"_rcpp_module_boot_stan_fit4indSigmat_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4indSigmat_mod, 0},
    {"_rcpp_module_boot_stan_fit4indSigmatHyperprior_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4indSigmatHyperprior_mod, 0},
    {"_rcpp_module_boot_stan_fit4indSigmatHyperpriorInequal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4indSigmatHyperpriorInequal_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_deconR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
