# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("errorModel2cellTypesHeirar", "errorModel2cellTypes", "errorModel", "indSigmatHyperpriorInequal", "indSigmatHyperprior", "indSigmatHyperpriorUnconstrained", "indSigmat")

# load each stan module
Rcpp::loadModule("stan_fit4errorModel2cellTypesHeirar_mod", what = TRUE)
Rcpp::loadModule("stan_fit4errorModel2cellTypes_mod", what = TRUE)
Rcpp::loadModule("stan_fit4errorModel_mod", what = TRUE)
Rcpp::loadModule("stan_fit4indSigmatHyperpriorInequal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4indSigmatHyperprior_mod", what = TRUE)
Rcpp::loadModule("stan_fit4indSigmatHyperpriorUnconstrained_mod", what = TRUE)
Rcpp::loadModule("stan_fit4indSigmat_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
